export const TEMP_DIR = './temp-docs'

export const autogeneratedDocs: ReadonlyArray<string> = [
  'ChainRec.ts',
  'Either.ts',
  'Identity.ts',
  'IO.ts',
  'IOEither.ts',
  'IOOption.ts',
  'Option.ts',
  'Reader.ts',
  'ReaderEither.ts',
  'ReaderTask.ts',
  'ReaderTaskEither.ts',
  'State.ts',
  'StateEither.ts',
  'StateIO.ts',
  'StateReaderTaskEither.ts',
  'StateTaskEither.ts',
  'Step.ts',
  'Task.ts',
  'TaskEither.ts',
  'TaskOption.ts',
]
